I'm sorry, but an uncaught exception occurred.

While running game code:
IOError: [Errno 2] No such file or directory: u'D:\\RELATIVISM-GAMES-STORAGE\\Supernova/game\\saves\\persistent.1572223253.tmp'

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "C:\Users\egora\Desktop\Софт\renpy-7.3.2-sdk\renpy\bootstrap.py", line 314, in bootstrap
    renpy.main.main()
  File "C:\Users\egora\Desktop\Софт\renpy-7.3.2-sdk\renpy\main.py", line 532, in main
    renpy.persistent.update(True)
  File "C:\Users\egora\Desktop\Софт\renpy-7.3.2-sdk\renpy\persistent.py", line 391, in update
    save()
  File "C:\Users\egora\Desktop\Софт\renpy-7.3.2-sdk\renpy\persistent.py", line 407, in save
    renpy.loadsave.location.save_persistent(data)
  File "C:\Users\egora\Desktop\Софт\renpy-7.3.2-sdk\renpy\savelocation.py", line 490, in save_persistent
    l.save_persistent(data)
  File "C:\Users\egora\Desktop\Софт\renpy-7.3.2-sdk\renpy\savelocation.py", line 347, in save_persistent
    with open(fn_tmp, "wb") as f:
IOError: [Errno 2] No such file or directory: u'D:\\RELATIVISM-GAMES-STORAGE\\Supernova/game\\saves\\persistent.1572223253.tmp'

Windows-8-6.2.9200
Ren'Py 7.3.2.320
Supernova 1.0
Mon Oct 28 04:33:52 2019
